/*
 * Lighthouse
 * © 2026 ayushshrivastv
 */

import LenisProvider from '@/src/providers/LenisProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'BlackIn',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <LenisProvider>{children}</LenisProvider>;
}
