/*
 * Lighthouse
 * © 2026 ayushshrivastv
 */

import type { Metadata } from 'next';
import ShortcutMenu from '@/src/components/utility/ShortcutMenuModal';
import { cookies } from 'next/headers';
import {
    getPlaygroundThemeBackgroundClass,
    getPlaygroundThemeRootClass,
    sanitizePlaygroundTheme,
} from '@/src/lib/playground-theme';

interface Props {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: 'BlackIn',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Props) {
    const cookieStore = await cookies();
    const cookieTheme = cookieStore.get('blackin_playground_theme')?.value;
    const initialTheme = sanitizePlaygroundTheme(cookieTheme);
    const initialThemeClass = getPlaygroundThemeRootClass(initialTheme);
    const initialBgClass = getPlaygroundThemeBackgroundClass(initialTheme);

    return (
        <div
            className={`playground-theme ${initialThemeClass} flex h-screen w-screen items-center justify-center ${initialBgClass}`}
        >
            {children}
            <ShortcutMenu />
        </div>
    );
}
